feat: footer update
antheiz/tripkepapua pull request #3
Opened 2023-01-22 06:02 UTC by danielcristho

2023-01-22 06:32 UTC, antheiz requested changes
Helo, Thanks!

Untuk setiap konten/teks/deskripsi gunakan bahasa Indonesia saja.
dan pastikan sebelum pr, buat pull dari repo master ini dulu wkwk takutnya ada yang mungkin sudah saya ubah.

2023-01-22 14:23 UTC, closed without merging

2023-01-22 14:23 UTC, danielcristho commented
close pr

2023-01-23 02:41 UTC, antheiz commented
> close pr

Yes, please create another PR
with like 

- About Us Page
- Footer

You can check reference in website like
- https://www.tripadvisor.com/
- https://www.klook.com/id/

2023-01-23 07:24 UTC, danielcristho commented
okay, thank you for the advice